import { IResolvers } from "graphql-tools";
import { Resolvers } from "./autogenerated-resolver-types";

export default function resolvers(): Resolvers<unknown> & Resolvers & IResolvers<any, any> {
    return {
        Query: {
            user: () => {
                return {
                    age: 8,
                    firstName: 'Oliver',
                    familyName: 'Jones',
                    dateOfBirth: '1994-02-21T00:00:00.000Z',
                    fullName: 'Oliver Gracy Jones',
                    favouriteFoods: ['Bananna', 'Pizza', 'Tadpoles']
                }
            }
        }
    }
};