import { IResolvers } from "graphql-tools";
import { Resolvers } from "./autogenerated-resolver-types";

export default function resolvers(): Resolvers<unknown> & Resolvers & IResolvers<any, any> {
    return {
        Query: {
            user: () => {
                return {
                    favouriteFoods: {
                        pageInfo: {
                            hasNextPage: false,
                            hasPreviousPage: false
                        },
                        edges: [
                            { node: { name: 'Bananna', pricePerKg: 10 }, cursor: 'abc' },
                            { node: { name: 'Pizza', pricePerKg: 10 }, cursor: 'abc' },
                            { node: { name: 'Tadpoles', pricePerKg: 10, }, cursor: 'abc' }
                        ]
                    }
                }
            }
        }
    }
};